create table if not exists public.community_rooms (
    id text primary key,
    university_key text not null,
    name text not null,
    description text default '',
    scope_label text default 'Custom',
    member_count integer not null default 1,
    is_verified boolean not null default true,
    is_auto_joined boolean not null default false,
    is_custom boolean not null default false,
    owner_user_id uuid null references auth.users(id) on delete set null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_community_rooms_university_key
    on public.community_rooms (university_key);

create table if not exists public.community_messages (
    id bigint generated by default as identity primary key,
    room_id text not null references public.community_rooms(id) on delete cascade,
    sender_id text,
    sender_name text not null,
    content text not null,
    image_url text,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_community_messages_room_created
    on public.community_messages (room_id, created_at);

alter table public.community_rooms enable row level security;
alter table public.community_messages enable row level security;

drop policy if exists "community rooms select" on public.community_rooms;
create policy "community rooms select"
on public.community_rooms
for select
to authenticated
using (true);

drop policy if exists "community rooms insert" on public.community_rooms;
create policy "community rooms insert"
on public.community_rooms
for insert
to authenticated
with check (true);

drop policy if exists "community rooms update" on public.community_rooms;
create policy "community rooms update"
on public.community_rooms
for update
to authenticated
using (owner_user_id is null or owner_user_id = auth.uid())
with check (owner_user_id is null or owner_user_id = auth.uid());

drop policy if exists "community rooms delete" on public.community_rooms;
create policy "community rooms delete"
on public.community_rooms
for delete
to authenticated
using (owner_user_id = auth.uid());

drop policy if exists "community messages select" on public.community_messages;
create policy "community messages select"
on public.community_messages
for select
to authenticated
using (true);

drop policy if exists "community messages insert" on public.community_messages;
create policy "community messages insert"
on public.community_messages
for insert
to authenticated
with check (true);